-- Packer
require 'plugins.packer'

-- Plugins configuration
-- require 'plugins.barbar'
-- require 'plugins.colorizer'
-- require 'plugins.comment'
-- require 'plugins.floaterm'
require 'plugins.fugitive'
require 'plugins.gitgutter'
-- require 'plugins.harpoon'
-- require 'plugins.lualine'
require 'plugins.markdown-preview'
-- require 'plugins.neorg'
-- require 'plugins.nvim-autopairs'
require 'plugins.nvim-cmp'
require 'plugins.nvim-tree'
-- require 'plugins.simpylfold'
-- require 'plugins.startify'
-- require 'plugins.tabnine'
-- require 'plugins.tagbar'
require 'plugins.telescope'
require 'plugins.treesitter'
-- require 'plugins.trouble'
require 'plugins.ultisnips'
require 'plugins.vimtex'
require 'plugins.vim-airline'
require 'plugins.vim-autoformat'
--require 'plugins.vim-tmux-navigator' -- buggy, cannot rotate threw split vim
--in two split tmux
